# Generated by Django 2.0.6 on 2018-06-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_data', models.CharField(max_length=8)),
                ('v_complete_data_number', models.IntegerField()),
                ('v_complete_data_string', models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='ClsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_oracle_user', models.CharField(max_length=30)),
                ('v_oracle_password', models.CharField(max_length=30)),
                ('lst_servers', models.TextField()),
                ('v_action', models.CharField(max_length=30)),
                ('v_sql_file', models.TextField()),
                ('v_csv_splitter', models.CharField(max_length=3)),
                ('v_sql_query', models.TextField()),
                ('v_path_export', models.TextField()),
                ('lst_file_export', models.TextField()),
                ('v_sql_loader_splitter', models.CharField(max_length=3)),
                ('v_sql_loader_owner', models.CharField(max_length=30)),
                ('v_sql_loader_table', models.CharField(max_length=30)),
                ('v_sql_loader_head', models.TextField()),
                ('v_sql_loader_constants', models.TextField()),
            ],
        ),
    ]
